baseURL = "https://www.locallyoptimistic.com/"
title = "Locally Optimistic"
theme = "hugo-nuo"

disqusShortname = "locallyoptimistic"
googleAnalytics = "UA-345857-22"

Paginate = 5
preserveTaxonomyNames = true
languageCode = "en"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Copyright of your post
copyright = "© Locally Optimistic"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Locally Optimistic"
  avatar = "/img/logo.png"
  seotitle = "Locally Optimisitc"
  subtitle = "A blog about data organizations"
  description = ""
  paginate = 10
